export {default as PrivateRoute} from '../Components/Private'
export {default as PrivateRoute3} from '../Components/Private3'
export {default as BarraSuperiorClub} from './BarraSuperiorClub'
export {default as BarraSuperiorJugador} from './BarraSuperiorJugador'
export {default as TablaClubes} from './TablaClubes'
export {default as TablaCampeonatos} from './TablaCampeonatos'
export {default as ResponsiveAppBar} from './AppBarInicio'